//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHSACH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhatHanhSachEntities : DbContext
    {
        public PhatHanhSachEntities()
            : base("name=PhatHanhSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAODL> BAOCAODL { get; set; }
        public virtual DbSet<CONGNO_DL> CONGNO_DL { get; set; }
        public virtual DbSet<CONGNO_NXB> CONGNO_NXB { get; set; }
        public virtual DbSet<CT_BAOCAODL> CT_BAOCAODL { get; set; }
        public virtual DbSet<CT_DOANHSO> CT_DOANHSO { get; set; }
        public virtual DbSet<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual DbSet<CT_PHIEUXUAT> CT_PHIEUXUAT { get; set; }
        public virtual DbSet<CHUCVU> CHUCVU { get; set; }
        public virtual DbSet<DAILY> DAILY { get; set; }
        public virtual DbSet<DOANHSO> DOANHSO { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNG { get; set; }
        public virtual DbSet<NHAXUATBAN> NHAXUATBAN { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAP { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUAT { get; set; }
        public virtual DbSet<SACH> SACH { get; set; }
        public virtual DbSet<TONKHO> TONKHO { get; set; }
        public virtual DbSet<TONKHODL> TONKHODL { get; set; }
    }
}
